<a href="https://colab.research.google.com/github/duller21/CPE15-Elective1/blob/main/NumPyBasicsWeek3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy (Numerical Python)
  *1. Python Library*

  *2. Linear algebra library for python*

  *3. already included in the anaconda distribution*

In [1]:
#import

import numpy as np
list_1 = [1,2,3,4]
type(list_1)

list

In [4]:
array_1= np.array(list_1)
type(array_1)

numpy.ndarray

In [5]:
#np.arange

np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [6]:
#np.arange na may intervals

np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
#np.zeros, np.ones

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
#np.zeros (with rows and columns)

np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#np.linspace

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
#np.eye

np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
#np.random.rand (randomizer) standard normal distribution

np.random.rand(5)

array([0.34531884, 0.30459652, 0.2541532 , 0.73999189, 0.34362304])

In [14]:
#np.random.rand (randomizer with no. of rows and columns)

np.random.rand(5,5)

array([[0.89995112, 0.15720972, 0.79818424, 0.01868618, 0.4633215 ],
       [0.43354354, 0.3080084 , 0.41709191, 0.9502915 , 0.96820798],
       [0.85280231, 0.72666875, 0.56159653, 0.77155101, 0.90993648],
       [0.26778784, 0.70982244, 0.91187646, 0.24871977, 0.44338969],
       [0.0231301 , 0.47546586, 0.28615292, 0.05053815, 0.4263923 ]])

In [15]:
#may negative

np.random.randn(5,5)

array([[-0.35460124,  0.60106208, -0.1260609 , -0.05187678,  0.5299833 ],
       [ 1.29883655, -1.2076645 ,  1.08058691, -1.69530515, -0.1798573 ],
       [-1.12731803,  1.1137142 ,  0.16845992,  0.34261142, -2.10943207],
       [-0.6456856 , -1.05981982,  1.28885859,  0.53494692, -0.85660413],
       [ 0.26509801,  0.66728875, -0.65021106, -0.01513453, -0.11949942]])

In [16]:
#np.random.randint

np.random.randint(1,20)

7

In [17]:
np.random.randint(1,20,5)

array([ 8, 16, 16,  5, 16])

In [18]:
x= np.random.randint(1,20,6)

In [19]:
x

array([ 7, 10, 17, 16, 17, 10])

In [21]:
#np.reshape (rows and columns)

x.reshape(2,3)

array([[ 7, 10, 17],
       [16, 17, 10]])

In [22]:
#np.array

slice = np.arange(1,51)

In [23]:
slice

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [24]:
a= slice.reshape(5,10)

In [25]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [28]:
#slice 3,4,5

a[0:1, 2:5]

array([[3, 4, 5]])

In [29]:
a[0:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [34]:
#slice 13,14; 22,24; 33,34

a[1:4, 2:4]

array([[13, 14],
       [23, 24],
       [33, 34]])

In [39]:
#slice 11,13; 22,23

row=[1,2]
column=[0,2]

a[row][:,column]

array([[11, 13],
       [21, 23]])