<a href="https://colab.research.google.com/github/duller21/CPE15-Elective1/blob/main/NumPyPart2Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##NumPy Array Indexing and Selection

In [1]:
import numpy as np
newArr = np.arange(0,16)

newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
newArr[9]

9

In [3]:
newArr[1:6]

array([1, 2, 3, 4, 5])

In [4]:
newArr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
newArr[10:]

array([10, 11, 12, 13, 14, 15])

In [8]:
newArr[:7] = 100

newArr

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

##Indexing a 2D Array (Matrix)

In [13]:
arr2D = np.array([2,4,6,8,10,12,14,16])
arr2D

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [15]:
arr2D.reshape(2,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [22]:
#Grabes the value of 2
arr2D[0]

2

In [24]:
#Grabs the value of the first row
arr2D = np.array([2,4,6,8,10,12,14,16]).reshape(2,4)
arr2D[0:1,0:4]

array([[2, 4, 6, 8]])

In [25]:
#Grabs the value of 16
arr2D = np.array([2,4,6,8,10,12,14,16]).reshape(2,4)
arr2D[1,3]

16

In [28]:
#Selecting submatrices
#[4,6]
#[10,12]
#[8,16]

arr2D[:,1:]

array([[ 4,  6,  8],
       [12, 14, 16]])

In [29]:
a = np.array([3,-4,8,5]).reshape(2,2)
b = np.array([9,-5,2,-6]).reshape(2,2)
c = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [31]:
a

array([[ 3, -4],
       [ 8,  5]])

In [32]:
b

array([[ 9, -5],
       [ 2, -6]])

In [33]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.add(a,b)

array([[12, -9],
       [10, -1]])

In [35]:
np.subtract(a,b)

array([[-6,  1],
       [ 6, 11]])

In [36]:
np.multiply(3,a)

array([[  9, -12],
       [ 24,  15]])

In [37]:
x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([5,6,7,8]).reshape(2,2)


In [38]:
x

array([[1, 2],
       [3, 4]])

In [39]:
y

array([[5, 6],
       [7, 8]])

In [40]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [41]:
r = np.array([1,2])
s = np.array([1,2]).reshape(2,1)


In [42]:
r

array([1, 2])

In [43]:
s

array([[1],
       [2]])

In [44]:
np.dot(r,s)

array([5])